// Audit attestation report renderer.
//
// Produces a single self-contained HTML document (inline CSS, zero external
// requests) suitable for archiving as evidence: it states what agent was tested,
// when, how many scenarios passed, how reproducible the behaviour was
// (determinism), the grounding/citation pass rate where applicable, and a
// per-scenario evidence table down to individual assertions and the judge
// verdict. The aesthetic is intentionally calm and document-like, modelled on a
// regulated attestation rather than a dashboard.

import type { AssertionResult, ScenarioRunSummary, SuiteReport } from '../core/types.js';
import {
  describeAssertion,
  groundingPassRate,
  isGroundingAssertion,
  pct,
  pct1,
  representativeRun,
} from './describe.js';

/** Optional document metadata stamped onto the attestation header. */
export interface HtmlReportMeta {
  /** Document title. Defaults to "Agent Reliability Attestation". */
  title?: string;
  /** The agent under test, shown in the header and summary. */
  agentName?: string;
  /** Who/what produced the report (tool + version), shown in the footer. */
  generatedBy?: string;
}

/**
 * Render the suite report as a self-contained HTML attestation document.
 * The returned string is a complete `<html>` document with all CSS inlined.
 */
export function renderHtml(report: SuiteReport, meta?: HtmlReportMeta): string {
  const title = meta?.title ?? 'Agent Reliability Attestation';
  const agentName = meta?.agentName ?? 'Unnamed agent';
  const generatedBy = meta?.generatedBy ?? 'AgentEval';

  const grounding = groundingPassRate(report);
  const overall = overallDeterminism(report);
  const isEmpty = report.totalScenarios === 0;
  const allPassed = report.passingScenarios === report.totalScenarios && !isEmpty;

  const summaryCards = [
    card('Scenarios passed', `${report.passingScenarios} / ${report.totalScenarios}`, allPassed ? 'ok' : 'warn'),
    card('Overall determinism', pct1(overall), overall >= 0.99 ? 'ok' : overall >= 0.8 ? 'warn' : 'bad'),
    grounding !== undefined
      ? card('Grounding pass rate', pct(grounding), grounding >= 0.99 ? 'ok' : grounding >= 0.8 ? 'warn' : 'bad')
      : '',
  ]
    .filter(Boolean)
    .join('\n');

  const verdictText = isEmpty ? 'NO SCENARIOS' : allPassed ? 'PASS' : 'ATTENTION REQUIRED';
  const verdictClass = isEmpty ? 'verdict-warn' : allPassed ? 'verdict-ok' : 'verdict-warn';

  const rows = report.scenarios.map(scenarioRow).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
${STYLES}
</style>
</head>
<body>
<main class="doc">
  <header class="head">
    <div class="brand">${esc(generatedBy)}</div>
    <h1>${esc(title)}</h1>
    <dl class="meta">
      <div><dt>Agent under test</dt><dd>${esc(agentName)}</dd></div>
      <div><dt>Generated</dt><dd>${esc(report.generatedAt)}</dd></div>
      <div><dt>Verdict</dt><dd><span class="${verdictClass}">${verdictText}</span></dd></div>
    </dl>
  </header>

  <section class="summary">
    <h2>Executive summary</h2>
    <div class="cards">
${summaryCards}
    </div>
    <p class="note">${esc(summaryProse(report, overall, grounding))}</p>
  </section>

  <section class="evidence">
    <h2>Scenario evidence</h2>
    <table>
      <thead>
        <tr>
          <th>Scenario</th>
          <th>Status</th>
          <th>Determinism</th>
          <th>Assertions</th>
          <th>Judge</th>
        </tr>
      </thead>
      <tbody>
${rows}
      </tbody>
    </table>
  </section>

  <footer class="foot">
    <p>This document is a point-in-time attestation of automated reliability testing. ${esc(report.totalScenarios.toString())} scenario(s) were evaluated. Generated by ${esc(generatedBy)}.</p>
  </footer>
</main>
</body>
</html>
`;
}

/** Mean determinism across scenarios (0..1); 1.0 when there are no scenarios. */
function overallDeterminism(report: SuiteReport): number {
  if (report.scenarios.length === 0) return 1;
  const sum = report.scenarios.reduce((acc, s) => acc + s.determinism, 0);
  return sum / report.scenarios.length;
}

/** A short prose sentence under the summary cards. No em dashes by design. */
function summaryProse(report: SuiteReport, overall: number, grounding: number | undefined): string {
  if (report.totalScenarios === 0) {
    return 'No scenarios were evaluated. Add scenarios and re-run to produce an attestation.';
  }
  const base = `${report.passingScenarios} of ${report.totalScenarios} scenarios met all assertions, with ${pct1(overall)} mean determinism across repeated runs.`;
  if (grounding === undefined) return base;
  return `${base} Grounding checks passed at ${pct(grounding)}.`;
}

/** One summary card. `tone` selects the accent colour. */
function card(label: string, value: string, tone: 'ok' | 'warn' | 'bad'): string {
  return `      <div class="cardItem tone-${tone}">
        <div class="cardValue">${esc(value)}</div>
        <div class="cardLabel">${esc(label)}</div>
      </div>`;
}

/** One evidence-table row for a scenario, including its assertion breakdown. */
function scenarioRow(s: ScenarioRunSummary): string {
  const rep = representativeRun(s);
  const status = s.pass
    ? '<span class="pill pill-ok">PASS</span>'
    : '<span class="pill pill-bad">FAIL</span>';

  const det = `${pct(s.determinism)} <span class="sub">${s.passingRuns}/${s.totalRuns}</span>`;

  const assertions = rep ? assertionList(rep.assertions) : '<span class="sub">no run captured</span>';

  let judgeCell = '<span class="sub">n/a</span>';
  if (rep?.judge) {
    const j = rep.judge;
    const jpill = j.pass ? 'pill-ok' : 'pill-bad';
    const verdict = j.pass ? 'PASS' : 'FAIL';
    judgeCell = `<span class="pill ${jpill}">${verdict}</span> <span class="sub">${j.passingVotes}/${j.votes} votes</span>`;
    if (j.detail) judgeCell += `<div class="detail">${esc(j.detail)}</div>`;
  }

  const errorRow = rep?.trace.error
    ? `<div class="errline">run error: ${esc(rep.trace.error)}</div>`
    : '';

  return `        <tr>
          <td class="scn"><code>${esc(s.scenarioId)}</code>${errorRow}</td>
          <td>${status}</td>
          <td>${det}</td>
          <td>${assertions}</td>
          <td>${judgeCell}</td>
        </tr>`;
}

/** Render the per-assertion list inside an evidence cell. */
function assertionList(results: readonly AssertionResult[]): string {
  if (results.length === 0) return '<span class="sub">none</span>';
  const items = results
    .map((r) => {
      const mark = r.pass ? '<span class="ok">PASS</span>' : '<span class="bad">FAIL</span>';
      const grounded = isGroundingAssertion(r.assertion) ? ' <span class="tag">grounding</span>' : '';
      const detail = r.detail && !r.pass ? `<div class="detail">${esc(r.detail)}</div>` : '';
      return `<li>${mark} ${esc(describeAssertion(r.assertion))}${grounded}${detail}</li>`;
    })
    .join('');
  return `<ul class="alist">${items}</ul>`;
}

/** HTML-escape text for safe interpolation into the document. */
function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Inline stylesheet. Calm, document-like, regulated-attestation aesthetic:
// serif headings, generous whitespace, restrained accent colours, a printable
// single-column layout.
const STYLES = `
:root {
  --ink: #1c1e21;
  --muted: #5b6470;
  --line: #e2e5ea;
  --bg: #f6f7f9;
  --paper: #ffffff;
  --ok: #1f7a4d;
  --ok-bg: #e8f3ec;
  --warn: #8a5a00;
  --warn-bg: #fbf2e0;
  --bad: #a3282b;
  --bad-bg: #f7e7e7;
  --accent: #243b53;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}
.doc {
  max-width: 980px;
  margin: 40px auto;
  background: var(--paper);
  border: 1px solid var(--line);
  border-radius: 10px;
  padding: 48px 56px;
  box-shadow: 0 1px 3px rgba(20,30,50,0.05);
}
h1, h2 { font-family: Georgia, "Times New Roman", serif; color: var(--accent); font-weight: 600; }
h1 { font-size: 28px; margin: 4px 0 24px; letter-spacing: 0.2px; }
h2 { font-size: 18px; margin: 36px 0 14px; padding-bottom: 6px; border-bottom: 1px solid var(--line); }
.head { border-bottom: 2px solid var(--accent); padding-bottom: 18px; }
.brand { font-size: 12px; letter-spacing: 2px; text-transform: uppercase; color: var(--muted); }
.meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin: 16px 0 0; }
.meta div { margin: 0; }
.meta dt { font-size: 11px; letter-spacing: 1px; text-transform: uppercase; color: var(--muted); }
.meta dd { margin: 2px 0 0; font-size: 15px; }
.verdict-ok { color: var(--ok); font-weight: 700; letter-spacing: 1px; }
.verdict-warn { color: var(--bad); font-weight: 700; letter-spacing: 1px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin: 8px 0 4px; }
.cardItem { border: 1px solid var(--line); border-radius: 8px; padding: 18px 20px; border-left: 4px solid var(--line); }
.cardItem.tone-ok { border-left-color: var(--ok); background: var(--ok-bg); }
.cardItem.tone-warn { border-left-color: var(--warn); background: var(--warn-bg); }
.cardItem.tone-bad { border-left-color: var(--bad); background: var(--bad-bg); }
.cardValue { font-size: 26px; font-weight: 700; font-family: Georgia, serif; }
.cardLabel { font-size: 12px; letter-spacing: 0.5px; color: var(--muted); margin-top: 4px; }
.note { color: var(--muted); font-size: 14px; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
thead th { text-align: left; font-size: 11px; letter-spacing: 1px; text-transform: uppercase; color: var(--muted); border-bottom: 2px solid var(--line); padding: 8px 10px; }
tbody td { border-bottom: 1px solid var(--line); padding: 12px 10px; vertical-align: top; }
.scn code { font-size: 13px; background: var(--bg); padding: 2px 6px; border-radius: 4px; }
.sub { color: var(--muted); font-size: 12px; }
.pill { display: inline-block; font-size: 11px; font-weight: 700; letter-spacing: 0.5px; padding: 2px 8px; border-radius: 999px; }
.pill-ok { color: var(--ok); background: var(--ok-bg); }
.pill-bad { color: var(--bad); background: var(--bad-bg); }
.alist { list-style: none; margin: 0; padding: 0; }
.alist li { padding: 3px 0; font-size: 13px; }
.ok { color: var(--ok); font-weight: 700; font-size: 11px; }
.bad { color: var(--bad); font-weight: 700; font-size: 11px; }
.tag { font-size: 10px; letter-spacing: 0.5px; text-transform: uppercase; color: var(--accent); background: var(--bg); padding: 1px 6px; border-radius: 4px; }
.detail { color: var(--bad); font-size: 12px; margin: 2px 0 0 4px; }
.errline { color: var(--bad); font-size: 12px; margin-top: 6px; }
.foot { margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; }
@media print { body { background: #fff; } .doc { border: none; box-shadow: none; margin: 0; max-width: none; } }
`;
